name: Docker Action
description: Run Docker container for SFTP upload

inputs:
  sftp-host:
    description: 'The SFTP host'
    required: true
  sftp-port:
    description: 'The SFTP port'
    required: true
    default: 22
  sftp-user:
    description: 'The SFTP username'
    required: true
  ssh-private-key:
    description: 'The SSH private key for authentication'
    required: true
  remote-path:
    description: 'The path on the remote server'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sftp-host }}
    - ${{ inputs.sftp-port }}
    - ${{ inputs.sftp-user }}
    - ${{ inputs.ssh-private-key }}
    - ${{ inputs.remote-path }}